from pprint import pprint

import requests

from parse_l2 import authorization_l2
from settings import login_l2, password_l2


def get_extract_number_by_number_history(connect, history_number: int):
    """Получает номер выписного эпикриза по номеру истории"""
    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'Content-Type': 'application/json',
        'DNT': '1',
        'Origin': 'http://192.168.10.161',
        'Proxy-Connection': 'keep-alive',
        'Referer': 'http://192.168.10.161/ui/stationar',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    }

    json_data = {
        'direction': history_number,  # номер истории (из таблицы)
        'r_type': 'extracts',
        'every': False,
    }

    response = connect.post(
        'http://192.168.10.161/api/stationar/directions-by-key',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()
    return response.get('data')[0].get('pk')


def create_expertise(connect, extract_number: int):
    """Создаёт лист экспертной оценки"""
    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'Content-Type': 'application/json',
        'DNT': '1',
        'Origin': 'http://192.168.10.161',
        'Proxy-Connection': 'keep-alive',
        'Referer': 'http://192.168.10.161/ui/stationar',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    }

    json_data = {
        'pk': extract_number,  # номер выписного эпикриза, не истории
    }

    response = connect.post(
        'http://192.168.10.161/api/directions/expertise-create',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()

    return response.get('pk')


def get_info_expertise(connect, exper_number: int):

    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'Content-Type': 'application/json',
        'DNT': '1',
        'Origin': 'http://192.168.10.161',
        'Proxy-Connection': 'keep-alive',
        'Referer': 'http://192.168.10.161/ui/results/descriptive?embedded=1&embeddedFull=1',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    }

    json_data = {
        'pk': exper_number,
        'searchMode': 'direction',
        'withoutIssledovaniye': None,
        'year': 2024,
    }

    response = connect.post(
        'http://192.168.10.161/api/directions/paraclinic_form',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()
    return {
        'pk_third': response.get('researches')[0].get('pk'),
        'date': response.get('researches')[0].get('examination_date')
    }


def save_expertise(connect, pk_third: int, pk_second: int, examination_date: str):

    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        'Content-Type': 'application/json',
        'DNT': '1',
        'Origin': 'http://192.168.10.161',
        'Proxy-Connection': 'keep-alive',
        'Referer': 'http://192.168.10.161/ui/results/descriptive?embedded=1&embeddedFull=1',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    }

    json_data = {
        'data': {
            'pk': pk_third,
            'amd': 'not_need',
            'amd_number': None,
            'direction_pk': pk_second,
            'research': {
                'pk': 1151,
                'title': 'Лист экспертной оценки II-III уровня',
                'version': int(f'{pk_third}0151'),
                'is_paraclinic': False,
                'is_doc_refferal': False,
                'is_gistology': False,
                'is_microbiology': False,
                'is_treatment': False,
                'is_stom': False,
                'isAux': False,
                'is_monitoring': False,
                'wide_headers': True,
                'comment': '',
                'groups': [
                    {
                        'pk': 3257,
                        'order': 1,
                        'title': 'Оценка качества оформления медицинской документации',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 17942,
                                'order': 1,
                                'lines': 1,
                                'title': 'Уровень экспертизы',
                                'hide': False,
                                'values_to_input': [
                                    '- Не выбрано',
                                    'второй',
                                    'третий',
                                ],
                                'value': 'второй',
                                'field_type': 10,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17870,
                                'order': 4,
                                'lines': 1,
                                'title': 'Полное и корректное заполнение титульного листа ИБ (группа крови, непереносимость лекарств, клинический диагноз, выполненные операции, исход заболевания, трудоспособность)',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17886,
                                'order': 5,
                                'lines': 3,
                                'title': 'Наличие правильно оформленных дневников (адекватное отображение состояния пациента, интерпретация результатов исследования, обоснование назначений), в т.ч. наличие дат и подписей',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17871,
                                'order': 6,
                                'lines': 3,
                                'title': 'Наличие правильно оформленных эпикризов (этапных, предоперационных, выписного), протоколов заседаний ВК, предоперационных концепций, протокол операции, в т.ч. наличие дат и подписей',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17872,
                                'order': 7,
                                'lines': 1,
                                'title': 'Наличие сопутствующего диагноза, диагностических и лечебных назначений после проведенных консультаций смежных специалистов. ',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17873,
                                'order': 8,
                                'lines': 3,
                                'title': 'Наличие полностью заполненного информированного добровольного согласия, отказа от лечения',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17874,
                                'order': 9,
                                'lines': 3,
                                'title': 'Отсутствие признаков искажения сведений, представленных в медицинской документации (дописки, исправления, "вклейки", полное переоформление с искажением сведений о проведенных диагностических и лечебных мероприятий, клинической картине заболевания; расхождение сведений об оказании медицинской помощи в различных разделах медицинской документации)',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17875,
                                'order': 10,
                                'lines': 1,
                                'title': 'Наличие в карте стационарного больного протокола врачебной комиссии в случаях назначения застрахованному лицу лекарственного препарата, не входящего в перечень жизненно необходимых и важнейших лекарственных препаратов.',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17876,
                                'order': 11,
                                'lines': 1,
                                'title': 'Комментарии при наличии одного отрицательного ответа ',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 3258,
                        'order': 2,
                        'title': 'Оценка качества медицинской помощи',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 17877,
                                'order': 1,
                                'lines': 1,
                                'title': 'Обследование соответствует стандартам, порядкам, национальным клиническим рекомендациям РФ  ',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '0',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17878,
                                'order': 2,
                                'lines': 3,
                                'title': 'Лечение соответствует стандартам, порядкам, национальным клиническим рекомендациям РФ',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '0',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17879,
                                'order': 3,
                                'lines': 3,
                                'title': 'Отсутствие осложнений, связанных с медицинским вмешательством/ оказанием медицинской помощи',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '0',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17880,
                                'order': 4,
                                'lines': 3,
                                'title': 'Результат достигнут (выздоровление, улучшение, без изменений) по основному заболеванию',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '0',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17881,
                                'order': 5,
                                'lines': 1,
                                'title': 'Комментарии при наличии одного отрицательного ответа ',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17882,
                                'order': 6,
                                'lines': 1,
                                'title': 'Отсутствие замечания по ведению истории болезни, не относящиеся к лечащему врачу (врач-консультант, заключения инструментальных/лабораторных исследований и др)',
                                'hide': False,
                                'values_to_input': [
                                    '+',
                                    '-',
                                ],
                                'value': '+',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '0',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 3259,
                        'order': 3,
                        'title': '',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 17883,
                                'order': 1,
                                'lines': 1,
                                'title': 'Комментарии при наличии отрицательного ответа',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17884,
                                'order': 2,
                                'lines': 1,
                                'title': 'Общее количество баллов',
                                'hide': False,
                                'values_to_input': [],
                                'value': 12,
                                'field_type': 3,
                                'can_edit': False,
                                'default_value': '("{17870}" === "+" && "{17871}" === "+" && "{17872}" === "+" && "{17873}" === "+" && "{17874}" === "+" && "{17875}" === "+" && "{17886}" === "+" ? 1 : 0) + ("{17877}" === "+" ? 2 : 0) + ("{17878}" === "+" ? 2 : 0) + ("{17879}" === "+" ? 5 : 0) + ("{17880}" === "+" ? 1 : 0) + ("{17882}" === "+" ? 1 : 0)',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17885,
                                'order': 3,
                                'lines': 1,
                                'title': 'Интерпретация баллов',
                                'hide': False,
                                'values_to_input': [],
                                'value': 'Замечаний нет',
                                'field_type': 3,
                                'can_edit': False,
                                'default_value': '{17884} >= 12 ? "Замечаний нет" : {17884} >= 10 && {17884} <= 11 ? "Несущественные замечания" : {17884} >= 8 && {17884} <= 9 ? "Существенные (создан риск для больного)" :  {17884} >= 6 && {17884} <= 7 ? "Серьезные (возникли осложнения)" : "Грубые, недопустимые"',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                            {
                                'pk': 17888,
                                'order': 5,
                                'lines': 3,
                                'title': 'Наличие замечаний',
                                'hide': False,
                                'values_to_input': [],
                                'value': 'Нет',
                                'field_type': 3,
                                'can_edit': False,
                                'default_value': '{17884} < 12 ? "Да" : "Нет"',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                ],
                'can_transfer': False,
                'is_extract': False,
                'transfer_direction': None,
                'transfer_direction_iss': [],
                'r_type': 'None',
                'show_more_services': True,
                'enabled_add_files': False,
                'is_need_send_egisz': False,
            },
            'pacs': None,
            'examination_date': examination_date,  # YYYY-mm-dd
            'templates': [
                {
                    'pk': 2617,
                    'title': 'По умолчанию',
                },
            ],
            'saved': False,
            'confirmed': False,
            'confirmed_at': None,
            'allow_reset_confirm': False,
            'more': [],
            'sub_directions': [],
            'recipe': [],
            'lab_comment': '',
            'forbidden_edit': True,
            'maybe_onco': False,
            'work_by': None,
            'tube': None,
            'procedure_list': [],
            'is_form': False,
            'children_directions': [],
            'parentDirection': {
                'pk': pk_second,
                'service': 'Выписка -тр',
                'is_hospital': False,
            },
            'whoSaved': None,
            'whoConfirmed': None,
            'whoExecuted': None,
            'countFiles': 0,
            'direction': {
                'pk': 2957054,
                'date': '07.07.2024',
                'all_confirmed': False,
                'diagnos': '',
                'fin_source': 'ОМС',
                'fin_source_id': 16,
                'priceCategory': '',
                'priceCategoryId': '',
                'additionalNumber': '',
                'additionalNumberYear': None,
                'timeGistologyReceive': None,
                'coExecutor': None,
                'tube': None,
                'amd': 'not_need',
                'amd_number': None,
                'hospitalTFOMSCode': '380017',
            },
            'coExecutor': None,
        },
        'with_confirm': True,
        'visibility_state': {
            'groups': {
                '3257': True,
                '3258': True,
                '3259': True,
            },
            'fields': {
                '17870': True,
                '17871': True,
                '17872': True,
                '17873': True,
                '17874': True,
                '17875': True,
                '17876': True,
                '17877': True,
                '17878': True,
                '17879': True,
                '17880': True,
                '17881': True,
                '17882': True,
                '17883': True,
                '17884': True,
                '17885': True,
                '17886': True,
                '17888': True,
                '17942': True,
            },
        },
    }

    response = connect.post(
        'http://192.168.10.161/api/directions/paraclinic_result',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()
    return response


session = requests.Session()

authorization_l2(session, login_l2, password_l2)

# first = get_extract_number_by_number_history(session, 2926888)
# print('Номер выписки: ', first)
#
# second = create_expertise(session, first)
# print(second)

third = get_info_expertise(session, 2957086)
pprint(third)
